/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.droiddice;

public final class R {
    public static final class anim {
        public static final int flip_from_bottom=0x7f040000;
        public static final int flip_to_top=0x7f040001;
        public static final int roll=0x7f040002;
        public static final int slide_in_down=0x7f040003;
        public static final int slide_in_up=0x7f040004;
    }
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textColor=0x7f010000;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), db (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSize=0x7f010001;
    }
    public static final class color {
        public static final int background_dark=0x7f050001;
        public static final int background_light=0x7f050000;
        public static final int db_bg_green=0x7f05000a;
        public static final int db_bg_red=0x7f050009;
        public static final int felt=0x7f05000b;
        public static final int felt_shadow=0x7f05000d;
        public static final int focus_border=0x7f050004;
        public static final int red=0x7f050005;
        public static final int result_text=0x7f05000c;
        public static final int selected_background_dark=0x7f050006;
        public static final int selected_light=0x7f050007;
        public static final int text_dark=0x7f050002;
        public static final int text_light=0x7f050003;
        public static final int transparent=0x7f050008;
    }
    public static final class dimen {
        public static final int die_padding=0x7f080003;
        public static final int die_value_text_size=0x7f080000;
        public static final int focus_border_thickness=0x7f080002;
        public static final int result_text_size=0x7f080001;
    }
    public static final class drawable {
        public static final int d100_60=0x7f020000;
        public static final int d10_60=0x7f020001;
        public static final int d12_60=0x7f020002;
        public static final int d20_60=0x7f020003;
        public static final int d4_60=0x7f020004;
        public static final int d6_60=0x7f020005;
        public static final int d8_60=0x7f020006;
        public static final int dice_set_button=0x7f020007;
        public static final int dice_set_button_selected=0x7f020008;
        public static final int felt=0x7f020009;
        public static final int felt_selected=0x7f02000a;
        public static final int felt_selector=0x7f02000b;
        public static final int icon=0x7f02000c;
        public static final int icon_d20=0x7f02000d;
        public static final int pulltab=0x7f02000e;
        public static final int shadow=0x7f02000f;
        public static final int title=0x7f020010;
    }
    public static final class id {
        public static final int dice_set_edit_activity_dice_set=0x7f090003;
        public static final int dice_set_edit_activity_die_selection=0x7f090004;
        public static final int dice_set_edit_activity_name=0x7f090002;
        public static final int dice_set_name=0x7f090000;
        public static final int dice_set_picture=0x7f090001;
        public static final int dice_set_selection_activity_grid=0x7f090005;
        public static final int dice_set_selection_item_dice=0x7f090007;
        public static final int dice_set_selection_item_die=0x7f090008;
        public static final int die_set_selection_item_name=0x7f090006;
        public static final int die_view_large=0x7f090009;
        public static final int roll_activity_dice_set=0x7f09000d;
        public static final int roll_activity_name=0x7f09000b;
        public static final int roll_activity_new_dice_set_selection=0x7f09000f;
        public static final int roll_activity_result=0x7f09000e;
        public static final int roll_activity_roll_area=0x7f09000a;
        public static final int roll_activity_roll_parent=0x7f09000c;
    }
    public static final class layout {
        public static final int dice_set=0x7f030000;
        public static final int dice_set_edit_activity=0x7f030001;
        public static final int dice_set_selection_activity=0x7f030002;
        public static final int dice_set_selection_item=0x7f030003;
        public static final int dice_view_large=0x7f030004;
        public static final int roll_activity=0x7f030005;
    }
    public static final class string {
        public static final int add_menu_text=0x7f060000;
        public static final int alert_dialog_cancel=0x7f060007;
        public static final int alert_dialog_ok=0x7f060006;
        public static final int app_name=0x7f060001;
        public static final int click_to_add=0x7f06000d;
        public static final int click_to_delete=0x7f06000e;
        public static final int confirm=0x7f060004;
        public static final int confirm_delete_dialog_text=0x7f060009;
        public static final int confirm_delete_dialog_title=0x7f060008;
        public static final int delete_menu_text=0x7f060005;
        public static final int dice=0x7f060003;
        public static final int dice_set_edit_add_button=0x7f06000a;
        public static final int dice_sets_label=0x7f06000c;
        public static final int edit_dice_sets_menu_text=0x7f06000f;
        public static final int edit_menu_text=0x7f06000b;
        public static final int name=0x7f060002;
    }
    public static final class style {
        public static final int Theme=0x7f070000;
    }
    public static final class styleable {
        /** Attributes that can be used with a com_droiddice_DiceSetEditView.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #com_droiddice_DiceSetEditView_textColor com.droiddice:textColor}</code><td></tr>
           <tr><th><code>{@link #com_droiddice_DiceSetEditView_textSize com.droiddice:textSize}</code><td></tr>
           </table>
           @see #com_droiddice_DiceSetEditView_textColor
           @see #com_droiddice_DiceSetEditView_textSize
         */
        public static final int[] com_droiddice_DiceSetEditView = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.droiddice.R.attr#textColor}
          attribute's value can be found in the {@link #com_droiddice_DiceSetEditView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textColor
        */
        public static final int com_droiddice_DiceSetEditView_textColor = 0;
        /**
          <p>This symbol is the offset where the {@link com.droiddice.R.attr#textSize}
          attribute's value can be found in the {@link #com_droiddice_DiceSetEditView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), db (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textSize
        */
        public static final int com_droiddice_DiceSetEditView_textSize = 1;
        /** Attributes that can be used with a com_droiddice_DiceSetView.
         */
        public static final int[] com_droiddice_DiceSetView = {
            
        };
        /** Attributes that can be used with a com_droiddice_RollAreaView.
         */
        public static final int[] com_droiddice_RollAreaView = {
            
        };
    };
}
